# Site settings
title: Barcelona Free Software - Meetup
email: barcelona-free-software@kde-espana.org
description: Barcelona Free Software is a meetup and an open space for coders and users who love free software (with +1400 members!)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bcnfs.github.io" # the base hostname & protocol for your site
twitter_username: BCNFreeSoftware
github_username:  bcnfs
meetup_username: Barcelona-Free-Software

# Build settings
markdown: kramdown
